import { Dimensions } from 'react-native';

const styles = {
  widgetWrapper: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    borderRadius: 10,
    height: 225,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E2E9EF',
    position: 'relative',
  },
  widgetHeader: {
    width: '100%',
    height: 35,
    position: 'absolute',
    backgroundColor: '#000',
    left: 0,
    top: 0,
    opacity: 0.8,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    overflow: 'hidden',
    paddingTop: 5,
    paddingLeft: 15,
    paddingRight: 15,
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    zIndex: 10,
  },
  camerasText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  camerasDetailText: {
    color: '#fff',
  },
  previewImageWrapper: {
    width: '100%',
    height: 175,
    position: 'relative',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: 175,
    position: 'relative',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    overflow: 'hidden',
  },
  controls: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingTop: 25,
    paddingLeft: 15,
    paddingRight: 15,
    flexDirection: 'row',
  },
  sliderLeftArrowWrapper: {
    flex: 1,
    alignItems: 'flex-start',
    paddingTop: 10,
    width: 55,
    height: 35,
  },
  sliderRightArrowWrapper: {
    flex: 1,
    alignItems: 'flex-end',
    paddingTop: 10,
    width: 55,
    height: 35,
  },
  sliderArrow: {
    width: 15,
    height: 15,
  },
  playButtonWrapper: {
    position: 'absolute',
    width: 100,
    height: 100,
    top: 50,
    left: (Dimensions.get('window').width / 2) - 55,
  },
  playButton: {
    width: 100,
    height: 100,
  },
};

export default styles;
