import ThemeVariables from '../../../smart-home-theme/variables/material';

const styles = {
  backgroundImage: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  logoView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoHide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    display: 'none',
  },
  mainLogo: {
    width: 85,
    height: 99,
    paddingHorizontal: 110,
    marginBottom: 20,
  },
  miniLogo: {
    width: 94,
    height: 76,
  },
  logoText: {
    fontSize: 24,
    fontFamily: 'Acrom-Medium',
    color: '#231f20',
  },
  mainTitle: {
    color: '#49A59A',
    fontWeight: 'bold',
    fontSize: 28,
    marginBottom: 45,
  },
  loginButton: {
    marginTop: '10%',
    borderRadius: 0,
    backgroundColor: ThemeVariables.mainApplicationColor,
  },
  loginFieldCaption: {
    width: '100%',
    textAlign: 'center',
    color: ThemeVariables.mainApplicationColor,
    backgroundColor: 'transparent',
    fontFamily: 'Acrom-Regular',
    fontSize: 12,
  },
  loginInput: {
    textAlign: 'center',
    borderBottomWidth: 0.4,
    height: 30,
    borderBottomColor: ThemeVariables.mainApplicationColor,
    color: '#231f20',
    fontFamily: 'Acrom-Regular',
    fontSize: 18,
    marginBottom: 10,
    padding: 0,
  },
  formItem: {
    borderStyle: 'solid',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
    width: '100%',
    borderBottomWidth: 0,
  },
  form: {
    width: '100%',
    flex: 1,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  formWrapper: {
    position: 'absolute',
    top: '40%',
    width: '80%',
    overflow: 'visible',
    zIndex: 9999,
    opacity: 0,
  },
  formWrapperTop: {
    position: 'absolute',
    top: '10%',
    width: '80%',
    overflow: 'visible',
    zIndex: 9999,
  },
  instructions: {
    backgroundColor: 'transparent',
    fontSize: 13,
    marginBottom: 50,
    lineHeight: 20,
    color: '#231f20',
    textAlign: 'center',
    fontFamily: 'Acrom-Regular',
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: -10,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF88',
  },
};

export default styles;
